// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_runs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextQueryRun = `-- name: ClaimNextQueryRun :one
WITH candidate AS (
    SELECT id
    FROM query_runs
    WHERE query_runs.daily_run_id = $3
      AND (
          (status = 'pending' AND next_attempt_at <= now())
          OR (status = 'running' AND locked_until <= now())
      )
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE query_runs
SET status = 'running',
    lease_token = $1,
    locked_until = now() + $2::bigint * interval '1 second',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = (SELECT id FROM candidate)
RETURNING id, daily_run_id, search_query_id, query_name, source_type, filters, status, jobs_found, new_jobs, error_text, lease_token, locked_until, started_at, completed_at, created_at, updated_at, rate_limit_attempts, next_attempt_at
`

type ClaimNextQueryRunParams struct {
	LeaseToken   pgtype.Text `json:"lease_token"`
	LeaseSeconds int64       `json:"lease_seconds"`
	RunID        int64       `json:"run_id"`
}

func (q *Queries) ClaimNextQueryRun(ctx context.Context, arg ClaimNextQueryRunParams) (QueryRun, error) {
	row := q.db.QueryRow(ctx, claimNextQueryRun, arg.LeaseToken, arg.LeaseSeconds, arg.RunID)
	var i QueryRun
	err := row.Scan(
		&i.ID,
		&i.DailyRunID,
		&i.SearchQueryID,
		&i.QueryName,
		&i.SourceType,
		&i.Filters,
		&i.Status,
		&i.JobsFound,
		&i.NewJobs,
		&i.ErrorText,
		&i.LeaseToken,
		&i.LockedUntil,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RateLimitAttempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const claimNotificationOutbox = `-- name: ClaimNotificationOutbox :one
WITH candidate AS (
    SELECT id
    FROM notification_outbox
    WHERE (
            status = 'pending'
            AND next_attempt_at <= now()
          )
       OR (
            status = 'processing'
            AND locked_until <= now()
          )
    ORDER BY next_attempt_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE notification_outbox
SET status = 'processing',
    attempts = attempts + 1,
    lease_token = $1,
    locked_until = now() + $2::bigint * interval '1 second',
    updated_at = now()
WHERE id = (SELECT id FROM candidate)
RETURNING id, daily_run_id, kind, chat_id, payload, status, attempts, next_attempt_at, lease_token, locked_until, last_error, sent_at, created_at, updated_at
`

type ClaimNotificationOutboxParams struct {
	LeaseToken   pgtype.Text `json:"lease_token"`
	LeaseSeconds int64       `json:"lease_seconds"`
}

func (q *Queries) ClaimNotificationOutbox(ctx context.Context, arg ClaimNotificationOutboxParams) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, claimNotificationOutbox, arg.LeaseToken, arg.LeaseSeconds)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.DailyRunID,
		&i.Kind,
		&i.ChatID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LockedUntil,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUnfinishedQueryRuns = `-- name: CountUnfinishedQueryRuns :one
SELECT count(*)
FROM query_runs
WHERE daily_run_id = $1
  AND status IN ('pending', 'running')
`

func (q *Queries) CountUnfinishedQueryRuns(ctx context.Context, dailyRunID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnfinishedQueryRuns, dailyRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failNotificationOutbox = `-- name: FailNotificationOutbox :execrows
UPDATE notification_outbox
SET status = 'failed',
    lease_token = NULL,
    locked_until = NULL,
    last_error = $3,
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
  AND lease_token = $2
`

type FailNotificationOutboxParams struct {
	ID         int64       `json:"id"`
	LeaseToken pgtype.Text `json:"lease_token"`
	LastError  string      `json:"last_error"`
}

func (q *Queries) FailNotificationOutbox(ctx context.Context, arg FailNotificationOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, failNotificationOutbox, arg.ID, arg.LeaseToken, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDailyRunByScheduleKey = `-- name: GetDailyRunByScheduleKey :one
SELECT id, scheduled_date, run_type, schedule_key, target_chat_id, status, query_count, failure_count, started_at, completed_at, created_at, updated_at
FROM daily_runs
WHERE schedule_key = $1
`

func (q *Queries) GetDailyRunByScheduleKey(ctx context.Context, scheduleKey pgtype.Text) (DailyRun, error) {
	row := q.db.QueryRow(ctx, getDailyRunByScheduleKey, scheduleKey)
	var i DailyRun
	err := row.Scan(
		&i.ID,
		&i.ScheduledDate,
		&i.RunType,
		&i.ScheduleKey,
		&i.TargetChatID,
		&i.Status,
		&i.QueryCount,
		&i.FailureCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDailyRunJob = `-- name: InsertDailyRunJob :exec
INSERT INTO daily_run_jobs (daily_run_id, job_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertDailyRunJobParams struct {
	DailyRunID int64 `json:"daily_run_id"`
	JobID      int64 `json:"job_id"`
}

func (q *Queries) InsertDailyRunJob(ctx context.Context, arg InsertDailyRunJobParams) error {
	_, err := q.db.Exec(ctx, insertDailyRunJob, arg.DailyRunID, arg.JobID)
	return err
}

const insertManualDailyRun = `-- name: InsertManualDailyRun :one
INSERT INTO daily_runs (scheduled_date, run_type, target_chat_id, query_count)
VALUES ($1, 'manual', $2, $3)
RETURNING id, scheduled_date, run_type, schedule_key, target_chat_id, status, query_count, failure_count, started_at, completed_at, created_at, updated_at
`

type InsertManualDailyRunParams struct {
	ScheduledDate pgtype.Date `json:"scheduled_date"`
	TargetChatID  int64       `json:"target_chat_id"`
	QueryCount    int32       `json:"query_count"`
}

func (q *Queries) InsertManualDailyRun(ctx context.Context, arg InsertManualDailyRunParams) (DailyRun, error) {
	row := q.db.QueryRow(ctx, insertManualDailyRun, arg.ScheduledDate, arg.TargetChatID, arg.QueryCount)
	var i DailyRun
	err := row.Scan(
		&i.ID,
		&i.ScheduledDate,
		&i.RunType,
		&i.ScheduleKey,
		&i.TargetChatID,
		&i.Status,
		&i.QueryCount,
		&i.FailureCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationOutbox = `-- name: InsertNotificationOutbox :exec
INSERT INTO notification_outbox (daily_run_id, kind, chat_id, payload)
VALUES ($1, 'daily_digest', $2, $3)
ON CONFLICT (daily_run_id) DO NOTHING
`

type InsertNotificationOutboxParams struct {
	DailyRunID int64           `json:"daily_run_id"`
	ChatID     int64           `json:"chat_id"`
	Payload    json.RawMessage `json:"payload"`
}

func (q *Queries) InsertNotificationOutbox(ctx context.Context, arg InsertNotificationOutboxParams) error {
	_, err := q.db.Exec(ctx, insertNotificationOutbox, arg.DailyRunID, arg.ChatID, arg.Payload)
	return err
}

const insertQueryRun = `-- name: InsertQueryRun :exec
INSERT INTO query_runs (
    daily_run_id,
    search_query_id,
    query_name,
    source_type,
    filters
)
VALUES ($1, $2, $3, $4, $5)
`

type InsertQueryRunParams struct {
	DailyRunID    int64           `json:"daily_run_id"`
	SearchQueryID int64           `json:"search_query_id"`
	QueryName     string          `json:"query_name"`
	SourceType    string          `json:"source_type"`
	Filters       json.RawMessage `json:"filters"`
}

func (q *Queries) InsertQueryRun(ctx context.Context, arg InsertQueryRunParams) error {
	_, err := q.db.Exec(ctx, insertQueryRun,
		arg.DailyRunID,
		arg.SearchQueryID,
		arg.QueryName,
		arg.SourceType,
		arg.Filters,
	)
	return err
}

const insertScheduledDailyRun = `-- name: InsertScheduledDailyRun :one
INSERT INTO daily_runs (scheduled_date, run_type, schedule_key, target_chat_id, query_count)
VALUES ($1, 'scheduled', $2, $3, $4)
ON CONFLICT (schedule_key) DO NOTHING
RETURNING id, scheduled_date, run_type, schedule_key, target_chat_id, status, query_count, failure_count, started_at, completed_at, created_at, updated_at
`

type InsertScheduledDailyRunParams struct {
	ScheduledDate pgtype.Date `json:"scheduled_date"`
	ScheduleKey   pgtype.Text `json:"schedule_key"`
	TargetChatID  int64       `json:"target_chat_id"`
	QueryCount    int32       `json:"query_count"`
}

func (q *Queries) InsertScheduledDailyRun(ctx context.Context, arg InsertScheduledDailyRunParams) (DailyRun, error) {
	row := q.db.QueryRow(ctx, insertScheduledDailyRun,
		arg.ScheduledDate,
		arg.ScheduleKey,
		arg.TargetChatID,
		arg.QueryCount,
	)
	var i DailyRun
	err := row.Scan(
		&i.ID,
		&i.ScheduledDate,
		&i.RunType,
		&i.ScheduleKey,
		&i.TargetChatID,
		&i.Status,
		&i.QueryCount,
		&i.FailureCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDailyRunJobs = `-- name: ListDailyRunJobs :many
SELECT jobs.id, jobs.source_type, jobs.source_key, jobs.external_id, jobs.title, jobs.company, jobs.location, jobs.url, jobs.posted_at, jobs.first_seen_at, jobs.last_seen_at
FROM daily_run_jobs
JOIN jobs ON jobs.id = daily_run_jobs.job_id
WHERE daily_run_jobs.daily_run_id = $1
ORDER BY daily_run_jobs.created_at, daily_run_jobs.job_id
`

func (q *Queries) ListDailyRunJobs(ctx context.Context, dailyRunID int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, listDailyRunJobs, dailyRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceKey,
			&i.ExternalID,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Url,
			&i.PostedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedQueryRuns = `-- name: ListFailedQueryRuns :many
SELECT id, daily_run_id, search_query_id, query_name, source_type, filters, status, jobs_found, new_jobs, error_text, lease_token, locked_until, started_at, completed_at, created_at, updated_at, rate_limit_attempts, next_attempt_at
FROM query_runs
WHERE daily_run_id = $1
  AND status = 'failed'
ORDER BY id
`

func (q *Queries) ListFailedQueryRuns(ctx context.Context, dailyRunID int64) ([]QueryRun, error) {
	rows, err := q.db.Query(ctx, listFailedQueryRuns, dailyRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryRun
	for rows.Next() {
		var i QueryRun
		if err := rows.Scan(
			&i.ID,
			&i.DailyRunID,
			&i.SearchQueryID,
			&i.QueryName,
			&i.SourceType,
			&i.Filters,
			&i.Status,
			&i.JobsFound,
			&i.NewJobs,
			&i.ErrorText,
			&i.LeaseToken,
			&i.LockedUntil,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RateLimitAttempts,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteDailyRuns = `-- name: ListIncompleteDailyRuns :many
SELECT id, scheduled_date, run_type, schedule_key, target_chat_id, status, query_count, failure_count, started_at, completed_at, created_at, updated_at
FROM daily_runs
WHERE status = 'running'
ORDER BY started_at, id
`

func (q *Queries) ListIncompleteDailyRuns(ctx context.Context) ([]DailyRun, error) {
	rows, err := q.db.Query(ctx, listIncompleteDailyRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyRun
	for rows.Next() {
		var i DailyRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledDate,
			&i.RunType,
			&i.ScheduleKey,
			&i.TargetChatID,
			&i.Status,
			&i.QueryCount,
			&i.FailureCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDailyRunCompleted = `-- name: MarkDailyRunCompleted :execrows
UPDATE daily_runs
SET status = 'completed',
    failure_count = $2,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
`

type MarkDailyRunCompletedParams struct {
	ID           int64 `json:"id"`
	FailureCount int32 `json:"failure_count"`
}

func (q *Queries) MarkDailyRunCompleted(ctx context.Context, arg MarkDailyRunCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDailyRunCompleted, arg.ID, arg.FailureCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationOutboxSent = `-- name: MarkNotificationOutboxSent :execrows
UPDATE notification_outbox
SET status = 'sent',
    lease_token = NULL,
    locked_until = NULL,
    last_error = '',
    sent_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
  AND lease_token = $2
`

type MarkNotificationOutboxSentParams struct {
	ID         int64       `json:"id"`
	LeaseToken pgtype.Text `json:"lease_token"`
}

func (q *Queries) MarkNotificationOutboxSent(ctx context.Context, arg MarkNotificationOutboxSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationOutboxSent, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markQueryRunFailed = `-- name: MarkQueryRunFailed :execrows
UPDATE query_runs
SET status = 'failed',
    error_text = $3,
    lease_token = NULL,
    locked_until = NULL,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND lease_token = $2
`

type MarkQueryRunFailedParams struct {
	ID         int64       `json:"id"`
	LeaseToken pgtype.Text `json:"lease_token"`
	ErrorText  string      `json:"error_text"`
}

func (q *Queries) MarkQueryRunFailed(ctx context.Context, arg MarkQueryRunFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markQueryRunFailed, arg.ID, arg.LeaseToken, arg.ErrorText)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markQueryRunSucceeded = `-- name: MarkQueryRunSucceeded :execrows
UPDATE query_runs
SET status = 'succeeded',
    jobs_found = $3,
    new_jobs = $4,
    error_text = '',
    lease_token = NULL,
    locked_until = NULL,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND lease_token = $2
`

type MarkQueryRunSucceededParams struct {
	ID         int64       `json:"id"`
	LeaseToken pgtype.Text `json:"lease_token"`
	JobsFound  int32       `json:"jobs_found"`
	NewJobs    int32       `json:"new_jobs"`
}

func (q *Queries) MarkQueryRunSucceeded(ctx context.Context, arg MarkQueryRunSucceededParams) (int64, error) {
	result, err := q.db.Exec(ctx, markQueryRunSucceeded,
		arg.ID,
		arg.LeaseToken,
		arg.JobsFound,
		arg.NewJobs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewQueryRunLease = `-- name: RenewQueryRunLease :execrows
UPDATE query_runs
SET locked_until = now() + $3::bigint * interval '1 second',
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND lease_token = $2
`

type RenewQueryRunLeaseParams struct {
	ID           int64       `json:"id"`
	LeaseToken   pgtype.Text `json:"lease_token"`
	LeaseSeconds int64       `json:"lease_seconds"`
}

func (q *Queries) RenewQueryRunLease(ctx context.Context, arg RenewQueryRunLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewQueryRunLease, arg.ID, arg.LeaseToken, arg.LeaseSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryNotificationOutbox = `-- name: RetryNotificationOutbox :execrows
UPDATE notification_outbox
SET status = 'pending',
    next_attempt_at = $3,
    lease_token = NULL,
    locked_until = NULL,
    last_error = $4,
    updated_at = now()
WHERE id = $1
  AND status = 'processing'
  AND lease_token = $2
`

type RetryNotificationOutboxParams struct {
	ID            int64              `json:"id"`
	LeaseToken    pgtype.Text        `json:"lease_token"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     string             `json:"last_error"`
}

func (q *Queries) RetryNotificationOutbox(ctx context.Context, arg RetryNotificationOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryNotificationOutbox,
		arg.ID,
		arg.LeaseToken,
		arg.NextAttemptAt,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryRateLimitedQueryRun = `-- name: RetryRateLimitedQueryRun :execrows
UPDATE query_runs
SET status = 'pending',
    rate_limit_attempts = rate_limit_attempts + 1,
    next_attempt_at = $3,
    error_text = $4,
    lease_token = NULL,
    locked_until = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND lease_token = $2
`

type RetryRateLimitedQueryRunParams struct {
	ID            int64              `json:"id"`
	LeaseToken    pgtype.Text        `json:"lease_token"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorText     string             `json:"error_text"`
}

func (q *Queries) RetryRateLimitedQueryRun(ctx context.Context, arg RetryRateLimitedQueryRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryRateLimitedQueryRun,
		arg.ID,
		arg.LeaseToken,
		arg.NextAttemptAt,
		arg.ErrorText,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
