// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hourly_search_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredHourlySearchQueries = `-- name: DeleteExpiredHourlySearchQueries :execrows
DELETE FROM hourly_search_queries
WHERE search_date < $1
`

func (q *Queries) DeleteExpiredHourlySearchQueries(ctx context.Context, searchDate pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredHourlySearchQueries, searchDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHourlySearchQueryBySearchQueryID = `-- name: DeleteHourlySearchQueryBySearchQueryID :execrows
DELETE FROM hourly_search_queries
WHERE search_query_id = $1
`

func (q *Queries) DeleteHourlySearchQueryBySearchQueryID(ctx context.Context, searchQueryID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHourlySearchQueryBySearchQueryID, searchQueryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHourlySearchQueryBySearchQueryID = `-- name: GetHourlySearchQueryBySearchQueryID :one
SELECT id, search_query_id, search_date, interval_minutes, next_run_at, created_at, updated_at
FROM hourly_search_queries
WHERE search_query_id = $1
`

func (q *Queries) GetHourlySearchQueryBySearchQueryID(ctx context.Context, searchQueryID int64) (HourlySearchQuery, error) {
	row := q.db.QueryRow(ctx, getHourlySearchQueryBySearchQueryID, searchQueryID)
	var i HourlySearchQuery
	err := row.Scan(
		&i.ID,
		&i.SearchQueryID,
		&i.SearchDate,
		&i.IntervalMinutes,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueHourlySearchQueries = `-- name: ListDueHourlySearchQueries :many
SELECT id, search_query_id, search_date, interval_minutes, next_run_at, created_at, updated_at
FROM hourly_search_queries
WHERE search_date = $1
  AND next_run_at <= $2
ORDER BY next_run_at, id
`

type ListDueHourlySearchQueriesParams struct {
	SearchDate pgtype.Date        `json:"search_date"`
	NextRunAt  pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) ListDueHourlySearchQueries(ctx context.Context, arg ListDueHourlySearchQueriesParams) ([]HourlySearchQuery, error) {
	rows, err := q.db.Query(ctx, listDueHourlySearchQueries, arg.SearchDate, arg.NextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlySearchQuery
	for rows.Next() {
		var i HourlySearchQuery
		if err := rows.Scan(
			&i.ID,
			&i.SearchQueryID,
			&i.SearchDate,
			&i.IntervalMinutes,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHourlySearchQueryNextRun = `-- name: UpdateHourlySearchQueryNextRun :exec
UPDATE hourly_search_queries
SET next_run_at = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateHourlySearchQueryNextRunParams struct {
	ID        int64              `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateHourlySearchQueryNextRun(ctx context.Context, arg UpdateHourlySearchQueryNextRunParams) error {
	_, err := q.db.Exec(ctx, updateHourlySearchQueryNextRun, arg.ID, arg.NextRunAt)
	return err
}

const upsertHourlySearchQuery = `-- name: UpsertHourlySearchQuery :one
INSERT INTO hourly_search_queries (search_query_id, search_date, interval_minutes, next_run_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (search_query_id) DO UPDATE SET
    search_date = EXCLUDED.search_date,
    interval_minutes = EXCLUDED.interval_minutes,
    next_run_at = EXCLUDED.next_run_at,
    updated_at = now()
RETURNING id, search_query_id, search_date, interval_minutes, next_run_at, created_at, updated_at
`

type UpsertHourlySearchQueryParams struct {
	SearchQueryID   int64              `json:"search_query_id"`
	SearchDate      pgtype.Date        `json:"search_date"`
	IntervalMinutes int32              `json:"interval_minutes"`
	NextRunAt       pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpsertHourlySearchQuery(ctx context.Context, arg UpsertHourlySearchQueryParams) (HourlySearchQuery, error) {
	row := q.db.QueryRow(ctx, upsertHourlySearchQuery,
		arg.SearchQueryID,
		arg.SearchDate,
		arg.IntervalMinutes,
		arg.NextRunAt,
	)
	var i HourlySearchQuery
	err := row.Scan(
		&i.ID,
		&i.SearchQueryID,
		&i.SearchDate,
		&i.IntervalMinutes,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
