// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
    source_type,
    source_key,
    external_id,
    title,
    company,
    location,
    url,
    posted_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source_type, source_key, external_id) DO NOTHING
RETURNING id, source_type, source_key, external_id, title, company, location, url, posted_at, first_seen_at, last_seen_at
`

type InsertJobParams struct {
	SourceType string             `json:"source_type"`
	SourceKey  string             `json:"source_key"`
	ExternalID string             `json:"external_id"`
	Title      string             `json:"title"`
	Company    string             `json:"company"`
	Location   string             `json:"location"`
	Url        string             `json:"url"`
	PostedAt   pgtype.Timestamptz `json:"posted_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.SourceType,
		arg.SourceKey,
		arg.ExternalID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Url,
		arg.PostedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceKey,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Url,
		&i.PostedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET title = $4,
    company = $5,
    location = $6,
    url = $7,
    posted_at = $8,
    last_seen_at = now()
WHERE source_type = $1
  AND source_key = $2
  AND external_id = $3
RETURNING id, source_type, source_key, external_id, title, company, location, url, posted_at, first_seen_at, last_seen_at
`

type UpdateJobParams struct {
	SourceType string             `json:"source_type"`
	SourceKey  string             `json:"source_key"`
	ExternalID string             `json:"external_id"`
	Title      string             `json:"title"`
	Company    string             `json:"company"`
	Location   string             `json:"location"`
	Url        string             `json:"url"`
	PostedAt   pgtype.Timestamptz `json:"posted_at"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.SourceType,
		arg.SourceKey,
		arg.ExternalID,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.Url,
		arg.PostedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.SourceKey,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Url,
		&i.PostedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
