// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          int64              `json:"id"`
	SourceType  string             `json:"source_type"`
	SourceKey   string             `json:"source_key"`
	ExternalID  string             `json:"external_id"`
	Title       string             `json:"title"`
	Company     string             `json:"company"`
	Location    string             `json:"location"`
	Url         string             `json:"url"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type SearchQuery struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	SourceType string             `json:"source_type"`
	Filters    json.RawMessage    `json:"filters"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
