// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type SearchQuery struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	SourceType string             `json:"source_type"`
	Filters    json.RawMessage    `json:"filters"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
