// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_queries.sql

package db

import (
	"context"
	"encoding/json"
)

const deleteSearchQueryByAnyID = `-- name: DeleteSearchQueryByAnyID :execrows
DELETE FROM search_queries
WHERE id = $1
`

func (q *Queries) DeleteSearchQueryByAnyID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSearchQueryByAnyID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSearchQueryByID = `-- name: DeleteSearchQueryByID :execrows
DELETE FROM search_queries
WHERE id = $1 AND source_type = $2
`

type DeleteSearchQueryByIDParams struct {
	ID         int64  `json:"id"`
	SourceType string `json:"source_type"`
}

func (q *Queries) DeleteSearchQueryByID(ctx context.Context, arg DeleteSearchQueryByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSearchQueryByID, arg.ID, arg.SourceType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSearchQueryByAnyID = `-- name: GetSearchQueryByAnyID :one
SELECT id, name, source_type, filters, enabled, created_at, updated_at
FROM search_queries
WHERE id = $1
`

func (q *Queries) GetSearchQueryByAnyID(ctx context.Context, id int64) (SearchQuery, error) {
	row := q.db.QueryRow(ctx, getSearchQueryByAnyID, id)
	var i SearchQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Filters,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSearchQueryByID = `-- name: GetSearchQueryByID :one
SELECT id, name, source_type, filters, enabled, created_at, updated_at
FROM search_queries
WHERE id = $1 AND source_type = $2
`

type GetSearchQueryByIDParams struct {
	ID         int64  `json:"id"`
	SourceType string `json:"source_type"`
}

func (q *Queries) GetSearchQueryByID(ctx context.Context, arg GetSearchQueryByIDParams) (SearchQuery, error) {
	row := q.db.QueryRow(ctx, getSearchQueryByID, arg.ID, arg.SourceType)
	var i SearchQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Filters,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSearchQueryByName = `-- name: GetSearchQueryByName :one
SELECT id, name, source_type, filters, enabled, created_at, updated_at
FROM search_queries
WHERE name = $1
`

func (q *Queries) GetSearchQueryByName(ctx context.Context, name string) (SearchQuery, error) {
	row := q.db.QueryRow(ctx, getSearchQueryByName, name)
	var i SearchQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Filters,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSearchQueries = `-- name: ListSearchQueries :many
SELECT id, name, source_type, filters, enabled, created_at, updated_at
FROM search_queries
ORDER BY name
`

func (q *Queries) ListSearchQueries(ctx context.Context) ([]SearchQuery, error) {
	rows, err := q.db.Query(ctx, listSearchQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchQuery
	for rows.Next() {
		var i SearchQuery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.Filters,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSearchQueryFilters = `-- name: UpdateSearchQueryFilters :one
UPDATE search_queries
SET filters = $3,
    updated_at = now()
WHERE id = $1 AND source_type = $2
RETURNING id, name, source_type, filters, enabled, created_at, updated_at
`

type UpdateSearchQueryFiltersParams struct {
	ID         int64           `json:"id"`
	SourceType string          `json:"source_type"`
	Filters    json.RawMessage `json:"filters"`
}

func (q *Queries) UpdateSearchQueryFilters(ctx context.Context, arg UpdateSearchQueryFiltersParams) (SearchQuery, error) {
	row := q.db.QueryRow(ctx, updateSearchQueryFilters, arg.ID, arg.SourceType, arg.Filters)
	var i SearchQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Filters,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSearchQuery = `-- name: UpsertSearchQuery :one
INSERT INTO search_queries (name, source_type, filters)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET
    source_type = EXCLUDED.source_type,
    filters = EXCLUDED.filters,
    updated_at = now()
RETURNING id, name, source_type, filters, enabled, created_at, updated_at
`

type UpsertSearchQueryParams struct {
	Name       string          `json:"name"`
	SourceType string          `json:"source_type"`
	Filters    json.RawMessage `json:"filters"`
}

func (q *Queries) UpsertSearchQuery(ctx context.Context, arg UpsertSearchQueryParams) (SearchQuery, error) {
	row := q.db.QueryRow(ctx, upsertSearchQuery, arg.Name, arg.SourceType, arg.Filters)
	var i SearchQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Filters,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
