// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_queries.sql

package db

import (
	"context"
	"encoding/json"
)

const getSearchQueryByName = `-- name: GetSearchQueryByName :one
SELECT id, name, source_type, filters, enabled, created_at, updated_at
FROM search_queries
WHERE name = $1
`

func (q *Queries) GetSearchQueryByName(ctx context.Context, name string) (SearchQuery, error) {
	row := q.db.QueryRow(ctx, getSearchQueryByName, name)
	var i SearchQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Filters,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSearchQueries = `-- name: ListSearchQueries :many
SELECT id, name, source_type, filters, enabled, created_at, updated_at
FROM search_queries
ORDER BY name
`

func (q *Queries) ListSearchQueries(ctx context.Context) ([]SearchQuery, error) {
	rows, err := q.db.Query(ctx, listSearchQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchQuery
	for rows.Next() {
		var i SearchQuery
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SourceType,
			&i.Filters,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchQuery = `-- name: UpsertSearchQuery :one
INSERT INTO search_queries (name, source_type, filters)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET
    source_type = EXCLUDED.source_type,
    filters = EXCLUDED.filters,
    updated_at = now()
RETURNING id, name, source_type, filters, enabled, created_at, updated_at
`

type UpsertSearchQueryParams struct {
	Name       string          `json:"name"`
	SourceType string          `json:"source_type"`
	Filters    json.RawMessage `json:"filters"`
}

func (q *Queries) UpsertSearchQuery(ctx context.Context, arg UpsertSearchQueryParams) (SearchQuery, error) {
	row := q.db.QueryRow(ctx, upsertSearchQuery, arg.Name, arg.SourceType, arg.Filters)
	var i SearchQuery
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.Filters,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
